# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: lightgallery # Pflichtfeld
version: '0.3.0' # Pflichtfeld
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/lightgallery

page:
    title: 'translate:title' # Werte die mit "translate:" beginnen, werden anhand der Sprachdatei übersetzt. Der Addon-Präfix (hier "lightgallery_") kann weggelassen werden.
    perm: lightgallery[]
    icon: rex-icon rex-icon-media
    subpages:
        info: { title: 'translate:info'}
        help: { title: 'translate:help'}
        changelog: { title: 'translate:changelog'}
        license: { title: 'translate:license'}
        #main: { title: 'translate:main' }
        #config: { title: 'translate:config', perm: 'lightgallery[config]', icon: rex-icon fa-wrench } # config-Seite mit separaten Rechten

requires:
    redaxo: '^5.0' # benötigt mindestens REDAXO 5.3
    packages:
        media_manager: '>=2.0.0' # benötigt mindestens das Addon Media Manager 2.3.0
    php:
        version: '>=5.6' # benötigt mindestens PHP 5.5
        #extensions: [gd, xml] # benötigt die PHP-Extensions GDlib und XML

# define conflicts: prevents packages from update to avoid breaking changes
# https://github.com/FriendsOfREDAXO/cache_warmup/pull/55#issuecomment-280906737
conflicts:
    packages:
        media_manager: '>=3'
        metainfo: '>=3'